/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedHabitsRouteImport } from './routes/_protected/habits'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedHabitsIndexRouteImport } from './routes/_protected/habits/index'
import { Route as ProtectedHabitsManageRouteImport } from './routes/_protected/habits/manage'
import { Route as ProtectedHabitsCreateRouteImport } from './routes/_protected/habits/create'
import { Route as ProtectedHabitsHabitIdEditRouteImport } from './routes/_protected/habits/$habitId.edit'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHabitsRoute = ProtectedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHabitsIndexRoute = ProtectedHabitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedHabitsRoute,
} as any)
const ProtectedHabitsManageRoute = ProtectedHabitsManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => ProtectedHabitsRoute,
} as any)
const ProtectedHabitsCreateRoute = ProtectedHabitsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ProtectedHabitsRoute,
} as any)
const ProtectedHabitsHabitIdEditRoute =
  ProtectedHabitsHabitIdEditRouteImport.update({
    id: '/$habitId/edit',
    path: '/$habitId/edit',
    getParentRoute: () => ProtectedHabitsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/habits': typeof ProtectedHabitsRouteWithChildren
  '/profile': typeof ProtectedProfileRoute
  '/habits/create': typeof ProtectedHabitsCreateRoute
  '/habits/manage': typeof ProtectedHabitsManageRoute
  '/habits/': typeof ProtectedHabitsIndexRoute
  '/habits/$habitId/edit': typeof ProtectedHabitsHabitIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/profile': typeof ProtectedProfileRoute
  '/habits/create': typeof ProtectedHabitsCreateRoute
  '/habits/manage': typeof ProtectedHabitsManageRoute
  '/habits': typeof ProtectedHabitsIndexRoute
  '/habits/$habitId/edit': typeof ProtectedHabitsHabitIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/habits': typeof ProtectedHabitsRouteWithChildren
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/habits/create': typeof ProtectedHabitsCreateRoute
  '/_protected/habits/manage': typeof ProtectedHabitsManageRoute
  '/_protected/habits/': typeof ProtectedHabitsIndexRoute
  '/_protected/habits/$habitId/edit': typeof ProtectedHabitsHabitIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/sso-callback'
    | '/dashboard'
    | '/habits'
    | '/profile'
    | '/habits/create'
    | '/habits/manage'
    | '/habits/'
    | '/habits/$habitId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sso-callback'
    | '/dashboard'
    | '/profile'
    | '/habits/create'
    | '/habits/manage'
    | '/habits'
    | '/habits/$habitId/edit'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/sso-callback'
    | '/_protected/dashboard'
    | '/_protected/habits'
    | '/_protected/profile'
    | '/_protected/habits/create'
    | '/_protected/habits/manage'
    | '/_protected/habits/'
    | '/_protected/habits/$habitId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/habits': {
      id: '/_protected/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof ProtectedHabitsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/habits/': {
      id: '/_protected/habits/'
      path: '/'
      fullPath: '/habits/'
      preLoaderRoute: typeof ProtectedHabitsIndexRouteImport
      parentRoute: typeof ProtectedHabitsRoute
    }
    '/_protected/habits/manage': {
      id: '/_protected/habits/manage'
      path: '/manage'
      fullPath: '/habits/manage'
      preLoaderRoute: typeof ProtectedHabitsManageRouteImport
      parentRoute: typeof ProtectedHabitsRoute
    }
    '/_protected/habits/create': {
      id: '/_protected/habits/create'
      path: '/create'
      fullPath: '/habits/create'
      preLoaderRoute: typeof ProtectedHabitsCreateRouteImport
      parentRoute: typeof ProtectedHabitsRoute
    }
    '/_protected/habits/$habitId/edit': {
      id: '/_protected/habits/$habitId/edit'
      path: '/$habitId/edit'
      fullPath: '/habits/$habitId/edit'
      preLoaderRoute: typeof ProtectedHabitsHabitIdEditRouteImport
      parentRoute: typeof ProtectedHabitsRoute
    }
  }
}

interface ProtectedHabitsRouteChildren {
  ProtectedHabitsCreateRoute: typeof ProtectedHabitsCreateRoute
  ProtectedHabitsManageRoute: typeof ProtectedHabitsManageRoute
  ProtectedHabitsIndexRoute: typeof ProtectedHabitsIndexRoute
  ProtectedHabitsHabitIdEditRoute: typeof ProtectedHabitsHabitIdEditRoute
}

const ProtectedHabitsRouteChildren: ProtectedHabitsRouteChildren = {
  ProtectedHabitsCreateRoute: ProtectedHabitsCreateRoute,
  ProtectedHabitsManageRoute: ProtectedHabitsManageRoute,
  ProtectedHabitsIndexRoute: ProtectedHabitsIndexRoute,
  ProtectedHabitsHabitIdEditRoute: ProtectedHabitsHabitIdEditRoute,
}

const ProtectedHabitsRouteWithChildren = ProtectedHabitsRoute._addFileChildren(
  ProtectedHabitsRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedHabitsRoute: typeof ProtectedHabitsRouteWithChildren
  ProtectedProfileRoute: typeof ProtectedProfileRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedHabitsRoute: ProtectedHabitsRouteWithChildren,
  ProtectedProfileRoute: ProtectedProfileRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SsoCallbackRoute: SsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
